### ISSUE TITLE
Help for another docker image maintainer...

### ISSUE THREAD

**Issue by fryfrog** [kc8apf/docker-unifi-video#6]
Hey @kc8apf,

I work on another Docker image for unifi-video and the 3.9.x -> 3.10.x upgrade is very frustrating. Does it just work for you and your users? Or do you have to jump through hoops like dumping and restoring the db and/or making a backup and restoring that?

My own personal instance is running 3.10.1 right now, but when I update to 3.10.2 it claims the user table is corrupt and logins don't work. In logs, I can see it also not recognizing the cameras that try to connect. Drop back to 3.10.1 and it fires up just fine. :/

**Comment by mx-shift** [comment]
I haven't had a chance to look into this yet. I haven't updated my image
recently so i wouldn't have run into this. I should have some time to look
into it next week.
